### ISSUE TITLE
Identity key issues (unreliable message sending)

### ISSUE THREAD

**Issue by julianfairfax** [whisperfish/presage#158] opened 2023-04-17 09:11 UTC
I am using Flare, by @Schmiddiii, and experiencing two issues:
- 1: Messages sent from Flare sometimes don't show up in the Signal Android app
  - The Signal Android app displays errors saying "a message from [your name] couldn't be delivered" and "chat session refreshed" in the note to self chat, despite the messages being received by the recipient.
  - It seems this solves itself, temporarily, randomly
- 2: Messages sent from Flare sometimes don't show up in Flare on other devices
  - It seems this is solved by relinking the affected Flare
- 3: Messages sent from Flare sometimes aren't received by recipients
  - The messages do show in Flare and in the Signal apps, giving you no indication that they failed to send
  - The recipient sees the same "a message from [your name] couldn't be delivered" in their chat with you
  - Or; you see issue 1, giving you an indication that the message failed to send, and the recipient sees nothing

Here's a log from Signal Android, for the first issue, and one from the affected Flare, for the second issue:
- [signal-log-1681666035397.zip](https://github.com/whisperfish/presage/files/11248327/signal-log-1681666035397.zip)
- [log.txt](https://github.com/whisperfish/presage/files/11298124/log.txt)

A potentially relevant part of the Signal log, highlighted by the developer:
```
[6.17.3] [62   ] 2023-04-16 19:26:50.196 GMT+02:00 W SignalServiceMessageSender: [handleMismatchedDevices] Address: ********-****-****-****-*********bed, ExtraDevices: [], MissingDevices: [1]
[6.17.3] [62   ] 2023-04-16 19:26:50.705 GMT+02:00 W SignalBaseIdentityKeySt: Received different identity key for self, ignoring | Existing: ******746, New: ******224
[6.17.3] [62   ] 2023-04-16 19:26:50.706 GMT+02:00 W BaseJob: java.io.IOException: Failed to resolve conflicts after 4 attempts!
```

This is a follow up to #152.

Edit: I've disabled my Signal PIN, cleared the Android app's data, and set it up from scratch. I will update this if I experience these issues again.

**Comment by TimMagee** [comment] 2023-04-21 15:05
> 3: Messages sent from Flare sometimes aren't received by recipients and didn't show in the Signal Android app
> 
>     * The messages do show in Flare and in the Signal desktop app, giving you no indication that they failed to send

I have this issue (but only for group messages).

I have never experienced any of the other described issues. I also never use Signal for Android. I just go back and forth between Desktop and Flare (I have Android but never open it).

**Comment by rubdos** [comment] 2023-04-21 15:41
Some comments:

- Decryption failures are handled in SA/iS by showing "could not be delivered", and then responding with a PlaintextContent(DecryptionError). IIRC, SA/iS would answer to such a notice by a session reset.
- If these decryption failures start appearing, this is an indication of session corruption. The root cause should be looked for, and it's usually an indicator of a crash of the receiving application during message decryption.

Concretely: the host application should implement such an automatic session reset (after double-checking with SA/SD/iS), and you need to find the root cause for possible session corruption.

In case of Whisperfish: we've had this before when there was a crash during message decryption. Since fixing the crashes and resetting all the corrupt sessions, this has not appeared any more.

**Comment by kaspar030** [comment] 2023-05-30 12:33
I'm seeing similar issues. I'm writing a [bot](https://github.com/kaspar030/sigbot) that transcribes incoming audio messages using whisper-rs.

I'm testing the bot with the Android app and a desktop Signal application. I get the same "bad encrypted MMS message" errors, and both the Signal desktop and Android app don't show some of the messages that my bot is sending (though some show with one, some show with the other).

What would be a proper way to reset this? (I can't reset my Android app, I don't want to loose all history).

How can I debug this?

**Comment by julianfairfax** [comment] 2023-08-27 10:07
I'm reopening this. It's sadly not fixed, and I have no idea what's causing it, let alone how to fix it. Unfortunately, it makes presage-based Signal apps unusable for those affected, so I'm hopeful there will one day be a solution.

**Comment by gferon** [comment] 2023-11-19 23:03
I believe this should be fixed with the last wave of changes. I'll close it because I'm happy with the changes and optimist, but feel free to reopen it if you see the issue again!

**Closed by gferon** 2023-11-19 23:03 UTC
